name: Continuous Delivery Flow

on:
  workflow_call:
    inputs:
      env_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        required: true
      GOOGLE_PROJECT:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }} manually
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-east1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/trietmapdit/${{ inputs.env_tag }}/nextjs-example:${{ github.sha }}
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: build and push the docker image
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Trigger Update Gitops
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${{github.sha}}`
            });

            await github.rest.actions.createWorkflowDispatch({
              owner: 'quangthien97',
              repo: 'example-gitops',
              workflow_id: 'deploy.yaml',
              ref: 'main',
              inputs: {
                repository: 'nextjs-example',
                image: '${{ env.IMAGE_NAME }}',
                env: '${{ inputs.env_tag }}',
                message: `${commit.data.commit.message.slice(0,200)}" -m "on ${{ github.event.ref }}" -m "by ${{ github.event.sender.login }}`,
              },
            });

